version: '3'
services:
  employee-database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
